# -*- coding: utf-8 -*-
"""Kmeans (Mall Customers Ex.)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7DHRRDg0JSUkVfTU2fH7EIFzWhjOVyE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import warnings
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv(r'Mall_Customers.csv')
df.head()

df.info()

df.rename(index=str,columns={'Annual Income (k$)':'Income',
                              'Spending Score (1-100)':'Score'},inplace=True)
df.head()

X=df.drop(['CustomerID','Gender'],axis=1)
sns.pairplot(df.drop('CustomerID',axis=1),hue='Gender',aspect=1.5)
plt.show()

from sklearn.cluster import KMeans

clusters=[]

for i in range(1,11):
  km=KMeans(n_clusters=i).fit(X)
  clusters.append(km.inertia_)

fig, ax = plt.subplots(figsize=(18,10))
sns.lineplot(x=list(range(1,11)),y=clusters,ax=ax,style=True,markers=True)
ax.set_title('Searching for Elbow')
ax.set_xlabel('Clusters')
ax.set_ylabel('Inertia')
plt.show()

# 3 CLusters
km3=KMeans(n_clusters=3).fit(X)

X['Labels']=km3.labels_
plt.figure(figsize=(18,10))
sns.scatterplot(X['Income'],X['Score'],hue=X['Labels'],palette=sns.color_palette('hls',3))
plt.title("KMeans with 3 Clusters")
plt.show()

# 5 CLusters
km5=KMeans(n_clusters=5).fit(X)

X['Labels']=km5.labels_
plt.figure(figsize=(18,10))
sns.scatterplot(X['Income'],X['Score'],hue=X['Labels'],palette=sns.color_palette('hls',5))
plt.title("KMeans with 5 Clusters")
plt.show()

fig=plt.figure(figsize=(20,8))
 ax=fig.add_subplot(121)
 sns.swarmplot(x='Labels',y='Income',data=X,ax=ax)
 ax.set_title('Labels According to Annual Income')

 ax=fig.add_subplot(122)
 sns.swarmplot(x='Labels',y='Score',data=X,ax=ax)
 ax.set_title('Labels According to Scoring History')

 plt.show()